# 关键帧
key_frame_distance: 2.0 # 关键帧距离

# 优化
graph_optimizer_type: gtsam # 图优化库，目前支持 [g2o, ceres, gtsam]

use_gnss: false
use_loop_close: true 

optimize_step_with_key_frame: 10000 # 没有其他信息时，每隔 step 发送一次优化的位姿
optimize_step_with_gnss: 950 # 每累计 step 个 gnss 观测时，优化一次
optimize_step_with_loop: 100  # 每累计 step 个闭环约束时优化一次

noise_model:
    odom:
        translation: [0.5, 0.5, 0.5]     # meter
        rotation: [0.001, 0.001, 0.001]  # rad
    close_loop:
        translation: [0.3, 0.3, 0.3]
        rotation: [0.001, 0.001, 0.001]
    gnss:
        translation: [2.0, 2.0, 2.0]

g2o:
    solver_type: lm_var_cholmod
    verbose: true

ceres:
    optimization_strategy: L-M # 优化方法，支持 L-M 和  Dog-Leg
    linear_solver_type: SPARSE_NORMAL_CHOLESKY # 线性求解器类型，ceres 默认使用普通的 QR，如果有第三方库，可以使用 SPARSE_NORMAL_CHOLESKY
    verbose: true

gtsam:
    verbose: SILENT
    optimization_strategy: LevenbergMarquardt
    linear_solver_type: MULTIFRONTAL_CHOLESKY